package it.polimi.ingsw.controller;

public enum Interaction {
    CHOOSEACTION,
    CHOOSEWEAPON,
    GRABWEAPON,
    RELOAD,
    MOVEPLAYER,
    CHOOSETARGET,
    MOVEENEMY,
    DISCARDPOWER,
    CHOOSEROOM,
    CHOOSEDIRECTION,
    CHOOSEPOSITION,
    GETNICKNAME,
    GETPHRASE,
    GETFIGHTER,
    GETSKULLSNUM,
    DISCARDWEAPON,
    CHOOSEMAP,
    CHOOSEFRENZY,
    CHOOSEPOWER,
    UPDATEVIEW,
    MESSAGE,
    PING
}