package it.polimi.ingsw.controller;

public enum Interaction {
    CHOOSEACTION,
    CHOOSEWEAPON,
    GRABWEAPON,
    RELOAD,
    MOVEPLAYER,
    CHOOSETARGET,
    MOVEENEMY,
    DISCARDPOWER,
    CHOOSEROOM,
    CHOOSEDIRECTION,
    CHOOSEPOSITION,
    DISCARDWEAPON
}