package it.polimi.ingsw.controller;

/**
 * Enumeration containing all the possible interactions used for network and GUI
 */
public enum Interaction {
    CHOOSEACTION,
    CHOOSEWEAPON,
    GRABWEAPON,
    DISCARDWEAPON,
    RELOAD,
    DISCARDPOWER,
    CHOOSEPOWER,
    MOVEPLAYER,
    CHOOSETARGET,
    MOVEENEMY,
    CHOOSEROOM,
    CHOOSEDIRECTION,
    CHOOSEPOSITION,
    CHOOSEMAP,
    CHOOSEFRENZY,
    GETNICKNAME,
    GETPHRASE,
    GETFIGHTER,
    GETSKULLSNUM,
    UPDATEVIEW,
    NONE,
    WAITINGUSER,
    SHOWINGMESSAGE,
    CLOSEAPP,
    RMIORSOCKET,
    SERVERIP,
    ASKLOCALADDRESS,
    CHOOSEBASEACTION,
    MESSAGE,
    PING,
    ENDGAME,
    CHOOSEWEAPONACTION,
    LOG,
    CHOOSEAMMO,
    DISCONNECTION
}